### PR TITLE
[WIP] passes/lower-mem: update for llvm 8

### PR DESCRIPTION
**Pull request by tomsik68**
only constants work for now

### CODE REVIEW

**Comment by versokova** [comment]
But it is working only for constants? Aren't you changing something else? Could you add testfolder for `lowermem`?

```diff
--- a/passes/test.sh.in
+++ b/passes/test.sh.in
@@ -34,6 +34,7 @@ mkdir -p "$LOG_PATH"
 #ps=$(find $REF_PATH -maxdepth 1 -type d -exec basename {} \;)
 ps="elim-const-expr
 global-vars
+lowermem
 global-vars -elim-const-expr"
```

**Comment by tomsik68** [comment]
I believe it only works for constants right now because of this: https://github.com/VeriFIT/ProStatA/pull/7/commits/5b2ac03a1c72820ef0349e096641845dd93a10d4#diff-ba94255458d60ffa15e7acbeef2d6b14R129-R151 . I should probably also preserve `} else { return false; }` from the condition. I'll add the testfolder in a moment.

**Comment by tomsik68** [comment]
Tests 06,08 and 12 revealed some problems. I tested the pass with Predator and it isn't helping where I was hoping it would. Please don't merge it as it is, I need to resolve these issues before merging. I'm marking it as work in progress.

**Comment by tomsik68** [comment]
This is no longer needed.

**Pull request closed without merging**
