### PR TITLE
passes/nestedgep: add tests

### PR DESCRIPTION
**Pull request by tomsik68**

### CODE REVIEW

**Comment by versokova** [comment]
Thanks. What is the point of having `01.c`? There is no nested gep different than in `02.c`. This nested gep is in both:
```
  %11 = getelementptr inbounds i8, i8* %10, i64 sub (i64 0, i64 mul nuw (i64 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i64), i64 2))
```

**Comment by tomsik68** [comment]
It is true that they are not too different: `01.c` contains one nested gep while `02.c` contains two of them. `01.c` is the smallest example I could find, so I thought it would be useful to leave it there. I can remove it if it's a problem.

**Comment by versokova** [comment]
Yes, it is the smallest (I guess), but you don't use `-nestedgep`.  02.c covers both situations - eliminate nested gep and ignore it. Please remove 01.c and I merge PR.

**Comment by tomsik68** [comment]
I force-pushed it so there won't be useless commits and renamed 02.c -> 01.c

**Comment by versokova** [comment]
Thank you!

**Pull request merged**
